---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default

  # WARNING: Do not use sqlite3. This is a FINANCIAL application, it needs a real database.

  adapter:  mysql 
  database: mostfit
  username: mostfituser
  password: mostfit_pass
  host:     localhost

test:
  <<:       *defaults
  database: mostfit_test
 
production:
  adapter:  mysql
  database: none
  username: mostfit
  password: 19te11eCAP
  host:     localhost

 
rake:
  <<: *defaults
